global:
  scrape_interval: 5s
  external_labels:
    cluster: hcm
    replica: 0

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9190']
  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9100']
remote_write:
- url: 'http://127.0.0.1:10908/api/v1/receive'
